### ISSUE TITLE
Unit test example

### ISSUE THREAD

**Issue by carloscheddar** [simplabs/ember-cli-simple-auth-example#7]
A `unit test` example for `simple-auth` would be useful since all examples that I've found are for `assertion tests`.

**Comment by marcoow** [comment]
Not sure what you mean. Are you looking for sample unit tests for e.g. custom authenticators?

**Comment by carloscheddar** [comment]
Sorry I should've been more specific.

I'm looking for a unit test example for this kind of situation.
http://stackoverflow.com/questions/29981454/ember-cli-unit-test-using-ember-cli-simple-auth 

Since the repo has assertion tests I felt that it should also provide unit tests examples here.
https://github.com/simplabs/ember-cli-simple-auth-example/tree/master/tests/unit

**Comment by marcoow** [comment]
See ms answer in stackoverflow.
